<template>
  <div class="nutrition">
    <Calendar />
    <Card v-for="(meal, index) in meals" :key="index" :content="meal" :isList=true />
  </div>
</template>

<script>
import Calendar from "@/components/Calendar.vue";
import Card from "@/components/Card.vue";
import GetData from "@/services/GetData.js";

export default {
  name: "Nutrition",
  components: {
    Calendar,
    Card
  },
  data() {
    return {
      meals: null
    }
  },
  created() {
    GetData.getNutrition()
      .then(response => {
        this.meals = response.data;
        console.log('[Meal response]', this.meals);
      })
      .catch(error => {
        console.log('[ERROR]', error)
      })
  }
};
</script>

<style scoped>
.nutrition {
  background-image: url("data:image/svg+xml,%3C%3Fxml version='1.0' encoding='utf-8'%3F%3E%3Csvg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' style='margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;' width='200px' height='200px' viewBox='0 0 100 100' preserveAspectRatio='xMidYMid'%3E%3Cg transform='rotate(0 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.9166666666666666s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(30 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.8333333333333334s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(60 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.75s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(90 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.6666666666666666s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(120 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.5833333333333334s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(150 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.5s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(180 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.4166666666666667s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(210 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.3333333333333333s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(240 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.25s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(270 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.16666666666666666s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(300 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='-0.08333333333333333s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3Cg transform='rotate(330 50 50)'%3E%3Crect x='48.5' y='24' rx='0' ry='0' width='3' height='12' fill='%2342b983'%3E%3Canimate attributeName='opacity' values='1;0' keyTimes='0;1' dur='1s' begin='0s' repeatCount='indefinite'%3E%3C/animate%3E%3C/rect%3E%3C/g%3E%3C!-- %5Bldio%5D generated by https://loading.io/ --%3E%3C/svg%3E");
  background-color: #fefefe;
  background-position: center;
  background-repeat: no-repeat;
  background-size: 80px;
  min-height: 100vh;
}
</style>
